export const DUMMY_COLLECTIONS_PRODUCTS = [
  {
    id: 1,
    model: 'De Gira',
    color: 'blanca',
    price: { raw: 3600, html: '3.600' },
    type: 'Remera',
    collections: 'remeras',
    url: 'remera-de-gira-blanca',
    image_top: require('assets/images/productos-remera-de-gira-blanca-1.jpg'),
    image_bottom: require('assets/images/productos-remera-de-gira-blanca-2.jpg'),
  },
  {
    id: 2,
    model: 'Ojos',
    color: 'negra',
    price: { raw: 3400, html: '3.400' },
    type: 'Remera',
    collections: 'remeras',
    url: 'remera-ojos-negra',
    image_top: require('assets/images/productos-remera-ojos-negra-1.jpg'),
    image_bottom: require('assets/images/productos-remera-ojos-negra-2.jpg'),
  },
  {
    id: 3,
    model: 'De Gira',
    color: 'blanco',
    price: { raw: 6400, html: '6.400' },
    type: 'Hoodie',
    collections: 'buzos',
    url: 'hoodie-de-gira-blanco',
    image_top: require('assets/images/productos-hoodie-de-gira-blanco-1.jpg'),
    image_bottom: require('assets/images/productos-hoodie-de-gira-blanco-2.jpg'),
  },
  {
    id: 4,
    model: 'De Gira',
    color: 'negro',
    price: { raw: 6400, html: '6.400' },
    type: 'Hoodie',
    collections: 'buzos',
    url: 'hoodie-de-gira-negro',
    image_top: require('assets/images/productos-hoodie-de-gira-negro-1.jpg'),
    image_bottom: require('assets/images/productos-hoodie-de-gira-negro-2.jpg'),
  },
  {
    id: 5,
    model: 'Flaakko',
    color: 'negro',
    price: { raw: 5600, html: '5.600' },
    type: 'Buzo',
    collections: 'buzos',
    url: 'buzo-flaakko-negro',
    image_top: require('assets/images/productos-buzo-flaakko-negro-1.jpg'),
    image_bottom: require('assets/images/productos-buzo-flaakko-negro-2.jpg'),
  },
  {
    id: 6,
    model: 'Baires',
    color: 'blanco',
    price: { raw: 3300, html: '3.300' },
    type: 'Gorro',
    collections: 'accesorios',
    url: 'gorro-baires-blanco',
    image_top: require('assets/images/productos-gorro-baires-blanco-1.jpg'),
    image_bottom: require('assets/images/productos-gorro-baires-blanco-2.jpg'),
  },
];
