export const DUMMY_PRODUCTS = [
  {
    id: 1,
    modelId: 1001,
    modelName: 'De Gira',
    variants: [
      {
        productId: 100101,
        color: 'blanca',
        price: { raw: 3600, html: '3.600' },
        type: 'Remera',
        collections: 'remeras',
        url: 'remera-de-gira-blanca',
        images: [
          require('assets/images/productos-remera-de-gira-blanca-1.jpg'),
          require('assets/images/productos-remera-de-gira-blanca-2.jpg'),
        ],
        inventoryLevels: [
          { talle: 'M', stock: 10 },
          { talle: 'L', stock: 12 },
          { talle: 'XL', stock: 22 },
          { talle: 'XXL', stock: 28 },
        ],
      },
    ],
  },
  {
    id: 2,
    modelId: 1002,
    modelName: 'Ojos',
    variants: [
      {
        productId: 100201,
        color: 'negra',
        price: { raw: 3400, html: '3.400' },
        type: 'Remera',
        collections: 'remeras',
        url: 'remera-ojos-negra',
        images: [
          require('assets/images/productos-remera-ojos-negra-1.jpg'),
          require('assets/images/productos-remera-ojos-negra-2.jpg'),
        ],
        inventoryLevels: [
          { talle: 'M', stock: 10 },
          { talle: 'L', stock: 12 },
          { talle: 'XL', stock: 22 },
          { talle: 'XXL', stock: 28 },
        ],
      },
    ],
  },
  {
    id: 3,
    modelId: 2001,
    modelName: 'De Gira',
    variants: [
      {
        productId: 200101,
        color: 'blanco',
        price: { raw: 6400, html: '6400' },
        type: 'Hoodie',
        collections: 'buzos',
        url: 'hoodie-de-gira-blanco',
        images: [
          require('assets/images/productos-hoodie-de-gira-blanco-1.jpg'),
          require('assets/images/productos-hoodie-de-gira-blanco-2.jpg'),
        ],
        inventoryLevels: [
          { talle: 'M', stock: 10 },
          { talle: 'L', stock: 12 },
          { talle: 'XL', stock: 22 },
          { talle: 'XXL', stock: 28 },
        ],
      },
      {
        productId: 200102,
        color: 'negro',
        price: { raw: 6400, html: '6400' },
        type: 'Hoodie',
        collections: 'buzos',
        url: 'hoodie-de-gira-negro',
        images: [
          require('assets/images/productos-hoodie-de-gira-negro-1.jpg'),
          require('assets/images/productos-hoodie-de-gira-negro-2.jpg'),
        ],
        inventoryLevels: [
          { talle: 'M', stock: 10 },
          { talle: 'L', stock: 12 },
          { talle: 'XL', stock: 22 },
          { talle: 'XXL', stock: 28 },
        ],
      },
    ],
  },
  {
    id: 4,
    modelId: 2002,
    modelName: 'Flaakko',
    variants: [
      {
        productId: 200201,
        color: 'negro',
        price: { raw: 5600, html: '5.600' },
        type: 'Buzo',
        collections: 'buzos',
        url: 'buzo-flaakko-negro',
        images: [
          require('assets/images/productos-buzo-flaakko-negro-1.jpg'),
          require('assets/images/productos-buzo-flaakko-negro-2.jpg'),
        ],
        inventoryLevels: [
          { talle: 'M', stock: 10 },
          { talle: 'L', stock: 12 },
          { talle: 'XL', stock: 22 },
          { talle: 'XXL', stock: 28 },
        ],
      },
    ],
  },
  {
    id: 5,
    modelId: 3001,
    modelName: 'Baires',
    variants: [
      {
        productId: 300101,
        color: 'blanco',
        price: { raw: 3300, html: '3.300' },
        type: 'Gorro',
        collections: 'accesorios',
        url: 'gorro-baires-blanco',
        images: [
          require('assets/images/productos-gorro-baires-blanco-1.jpg'),
          require('assets/images/productos-gorro-baires-blanco-2.jpg'),
        ],
        inventoryLevels: [
          { talle: 'M', stock: 10 },
          { talle: 'L', stock: 12 },
          { talle: 'XL', stock: 22 },
          { talle: 'XXL', stock: 28 },
        ],
      },
    ],
  },
];

// export const DUMMY_PRODUCTS = [
//   {
//     id: 1,
//     model: 'De Gira',
//     color: 'blanca',
//     price: { raw: 3600, html: '3.600' },
//     type: 'Remera',
//     collections: 'remeras',
//     url: 'remera-de-gira-blanca',
//     image_top: require('assets/images/productos-remera-de-gira-blanca-1.jpg'),
//     image_bottom: require('assets/images/productos-remera-de-gira-blanca-2.jpg'),
//   },
//   {
//     id: 2,
//     model: 'Ojos',
//     color: 'negra',
//     price: { raw: 3400, html: '3.400' },
//     type: 'Remera',
//     collections: 'remeras',
//     url: 'remera-ojos-negra',
//     image_top: require('assets/images/productos-remera-ojos-negra-1.jpg'),
//     image_bottom: require('assets/images/productos-remera-ojos-negra-2.jpg'),
//   },
//   {
//     id: 3,
//     model: 'De Gira',
//     color: 'blanco',
//     price: { raw: 6400, html: '6.400' },
//     type: 'Hoodie',
//     collections: 'buzos',
//     url: 'hoodie-de-gira-blanco',
//     image_top: require('assets/images/productos-hoodie-de-gira-blanco-1.jpg'),
//     image_bottom: require('assets/images/productos-hoodie-de-gira-blanco-2.jpg'),
//   },
//   {
//     id: 4,
//     model: 'De Gira',
//     color: 'negro',
//     price: { raw: 6400, html: '6.400' },
//     type: 'Hoodie',
//     collections: 'buzos',
//     url: 'remera-de-gira-negro',
//     image_top: require('assets/images/productos-hoodie-de-gira-negro-1.jpg'),
//     image_bottom: require('assets/images/productos-hoodie-de-gira-negro-2.jpg'),
//   },
//   {
//     id: 5,
//     model: 'Flaakko',
//     color: 'negro',
//     price: { raw: 5600, html: '5.600' },
//     type: 'Buzo',
//     collections: 'buzos',
//     url: 'buzo-flaakko-negro',
//     image_top: require('assets/images/productos-buzo-flaakko-negro-1.jpg'),
//     image_bottom: require('assets/images/productos-buzo-flaakko-negro-2.jpg'),
//   },
//   {
//     id: 6,
//     model: 'Baires',
//     color: 'blanco',
//     price: { raw: 3300, html: '3.300' },
//     type: 'Gorro',
//     collections: 'accesorios',
//     url: 'gorro-baires-blanco',
//     image_top: require('assets/images/productos-gorro-baires-blanco-1.jpg'),
//     image_bottom: require('assets/images/productos-gorro-baires-blanco-2.jpg'),
//   },
// ];
